### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by hoang6** [scikit-nano/scikit-nano#7]
Hello Andrew,

I created graphene sheet using your package, it's very nice. However, it seems to have a problem with the periodic boundary (please check the image attached). I'm going over the codes, but would you mind double check that as well?

Thank you for your help (and the scikit-nano package)!

Tom
![screen shot 2016-06-24 at 2 36 10 pm](https://cloud.githubusercontent.com/assets/2857972/16348760/1f4da962-3a1a-11e6-96ce-48fbd1ce041d.png)

**Comment by the-real-droop** [comment]
@hoang6, Sorry for this unfortunate regression. I'm a bit preoccupied with other things at the moment, but I'll look into this ASAP and will follow-up.

**Comment by hoang6** [comment]
Thanks, Andrew!

**Comment by the-real-droop** [comment]
@hoang6, if possible, can you please give me the commands you used to generate the structure?

Also, which version are you running?

Thanks,
Andrew

**Comment by hoang6** [comment]
Hi Andrew,

I'm very sorry for this late response! I used these commands to generate the graphene structures:

from sknano.generators import GrapheneGenerator
ACG = GrapheneGenerator(armchair_edge_length=10, zigzag_edge_length=10)
ACG.save()

I believe I cloned the most current version from your repo. I believe there's nothing wrong with the structure, but changing the simulation cell dimension will make it right?

Thanks for your help!

Tom

**Comment by the-real-droop** [comment]
Hi Tom. Ok, let's back up. It seems you generated the periodic structure shown in your screenshot using software? If so, which software? And was it using the XYZ output?

I think that might be the issue as the XYZ output does not retain any information about the crystal cell, which the software needs to know in order to create the correct periodic boundaries.

Let me know if this is the case and then I can help come up with some other options for doing what you want.

Thanks,
Andrew

**Comment by hoang6** [comment]
Hello Andrew,

Yes, I used OVITO to generate the periodic structure, and it used the XYZ output. OVITO can use LAMMPS data file as well, but I'm not sure how the generate LAMMPS data file from scikit-nano. Can you please tell me how?

Thanks for your help!
Tom

**Comment by the-real-droop** [comment]
Hi Tom,

To save structure data as a LAMMPS data file, you can call the save method using a custom file name with a `'.data'` extension, or call the save method with `structure_format='data'` keyword argument, i.e.:

`ACG.save(fname='graphene.data')`
or
`ACG.save(structure_format='data')`

I came across a bug in the crystal cell bounds when saving the structure data to LAMMPS data format, which I've fixed in the latest development branch.

Pull the latest code, checkout and install from the `dev` branch, and you should now be able to visualize the graphene structure with the correct PBC.

Thanks for using my code and bringing this bug to my attention. Let me know if you run into any problems.

Andrew

**Comment by hoang6** [comment]
Thanks for your kind help, Andrew!

Tom
